/* 
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test
{
    /// <summary>
    ///  Class for testing AwsS3LogForwardingConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwsS3LogForwardingConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwsS3LogForwardingConfig
        //private AwsS3LogForwardingConfig instance;

        public AwsS3LogForwardingConfigTests()
        {
            // TODO uncomment below to create an instance of AwsS3LogForwardingConfig
            //instance = new AwsS3LogForwardingConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwsS3LogForwardingConfig
        /// </summary>
        [Fact]
        public void AwsS3LogForwardingConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AwsS3LogForwardingConfig
            //Assert.IsInstanceOfType<AwsS3LogForwardingConfig> (instance, "variable 'instance' is a AwsS3LogForwardingConfig");
        }


        /// <summary>
        /// Test the property 'AwsAccessId'
        /// </summary>
        [Fact]
        public void AwsAccessIdTest()
        {
            // TODO unit test for the property 'AwsAccessId'
        }
        /// <summary>
        /// Test the property 'AwsAccessKey'
        /// </summary>
        [Fact]
        public void AwsAccessKeyTest()
        {
            // TODO unit test for the property 'AwsAccessKey'
        }
        /// <summary>
        /// Test the property 'AwsRegion'
        /// </summary>
        [Fact]
        public void AwsRegionTest()
        {
            // TODO unit test for the property 'AwsRegion'
        }
        /// <summary>
        /// Test the property 'BucketName'
        /// </summary>
        [Fact]
        public void BucketNameTest()
        {
            // TODO unit test for the property 'BucketName'
        }
        /// <summary>
        /// Test the property 'LogFolder'
        /// </summary>
        [Fact]
        public void LogFolderTest()
        {
            // TODO unit test for the property 'LogFolder'
        }

    }

}
