/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCertificateOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCertificateOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCertificateOutput
        //private CreateCertificateOutput instance;

        public CreateCertificateOutputTests()
        {
            // TODO uncomment below to create an instance of CreateCertificateOutput
            //instance = new CreateCertificateOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCertificateOutput
        /// </summary>
        [Fact]
        public void CreateCertificateOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCertificateOutput
            //Assert.IsType<CreateCertificateOutput>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
