/* 
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test
{
    /// <summary>
    ///  Class for testing CreateAuthMethodUniversalIdentity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAuthMethodUniversalIdentityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAuthMethodUniversalIdentity
        //private CreateAuthMethodUniversalIdentity instance;

        public CreateAuthMethodUniversalIdentityTests()
        {
            // TODO uncomment below to create an instance of CreateAuthMethodUniversalIdentity
            //instance = new CreateAuthMethodUniversalIdentity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAuthMethodUniversalIdentity
        /// </summary>
        [Fact]
        public void CreateAuthMethodUniversalIdentityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateAuthMethodUniversalIdentity
            //Assert.IsInstanceOfType<CreateAuthMethodUniversalIdentity> (instance, "variable 'instance' is a CreateAuthMethodUniversalIdentity");
        }


        /// <summary>
        /// Test the property 'AccessExpires'
        /// </summary>
        [Fact]
        public void AccessExpiresTest()
        {
            // TODO unit test for the property 'AccessExpires'
        }
        /// <summary>
        /// Test the property 'BoundIps'
        /// </summary>
        [Fact]
        public void BoundIpsTest()
        {
            // TODO unit test for the property 'BoundIps'
        }
        /// <summary>
        /// Test the property 'DenyInheritance'
        /// </summary>
        [Fact]
        public void DenyInheritanceTest()
        {
            // TODO unit test for the property 'DenyInheritance'
        }
        /// <summary>
        /// Test the property 'DenyRotate'
        /// </summary>
        [Fact]
        public void DenyRotateTest()
        {
            // TODO unit test for the property 'DenyRotate'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }

    }

}
