/* 
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test
{
    /// <summary>
    ///  Class for testing DescribeItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DescribeItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DescribeItem
        //private DescribeItem instance;

        public DescribeItemTests()
        {
            // TODO uncomment below to create an instance of DescribeItem
            //instance = new DescribeItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DescribeItem
        /// </summary>
        [Fact]
        public void DescribeItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DescribeItem
            //Assert.IsInstanceOfType<DescribeItem> (instance, "variable 'instance' is a DescribeItem");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ShowVersions'
        /// </summary>
        [Fact]
        public void ShowVersionsTest()
        {
            // TODO unit test for the property 'ShowVersions'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }

    }

}
