/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing DynamicSecretCreatePostgreSql
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DynamicSecretCreatePostgreSqlTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DynamicSecretCreatePostgreSql
        //private DynamicSecretCreatePostgreSql instance;

        public DynamicSecretCreatePostgreSqlTests()
        {
            // TODO uncomment below to create an instance of DynamicSecretCreatePostgreSql
            //instance = new DynamicSecretCreatePostgreSql();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DynamicSecretCreatePostgreSql
        /// </summary>
        [Fact]
        public void DynamicSecretCreatePostgreSqlInstanceTest()
        {
            // TODO uncomment below to test "IsType" DynamicSecretCreatePostgreSql
            //Assert.IsType<DynamicSecretCreatePostgreSql>(instance);
        }


        /// <summary>
        /// Test the property 'CreationStatements'
        /// </summary>
        [Fact]
        public void CreationStatementsTest()
        {
            // TODO unit test for the property 'CreationStatements'
        }
        /// <summary>
        /// Test the property 'DeleteProtection'
        /// </summary>
        [Fact]
        public void DeleteProtectionTest()
        {
            // TODO unit test for the property 'DeleteProtection'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PasswordLength'
        /// </summary>
        [Fact]
        public void PasswordLengthTest()
        {
            // TODO unit test for the property 'PasswordLength'
        }
        /// <summary>
        /// Test the property 'PostgresqlDbName'
        /// </summary>
        [Fact]
        public void PostgresqlDbNameTest()
        {
            // TODO unit test for the property 'PostgresqlDbName'
        }
        /// <summary>
        /// Test the property 'PostgresqlHost'
        /// </summary>
        [Fact]
        public void PostgresqlHostTest()
        {
            // TODO unit test for the property 'PostgresqlHost'
        }
        /// <summary>
        /// Test the property 'PostgresqlPassword'
        /// </summary>
        [Fact]
        public void PostgresqlPasswordTest()
        {
            // TODO unit test for the property 'PostgresqlPassword'
        }
        /// <summary>
        /// Test the property 'PostgresqlPort'
        /// </summary>
        [Fact]
        public void PostgresqlPortTest()
        {
            // TODO unit test for the property 'PostgresqlPort'
        }
        /// <summary>
        /// Test the property 'PostgresqlUsername'
        /// </summary>
        [Fact]
        public void PostgresqlUsernameTest()
        {
            // TODO unit test for the property 'PostgresqlUsername'
        }
        /// <summary>
        /// Test the property 'ProducerEncryptionKey'
        /// </summary>
        [Fact]
        public void ProducerEncryptionKeyTest()
        {
            // TODO unit test for the property 'ProducerEncryptionKey'
        }
        /// <summary>
        /// Test the property 'RevocationStatement'
        /// </summary>
        [Fact]
        public void RevocationStatementTest()
        {
            // TODO unit test for the property 'RevocationStatement'
        }
        /// <summary>
        /// Test the property 'SecureAccessBastionIssuer'
        /// </summary>
        [Fact]
        public void SecureAccessBastionIssuerTest()
        {
            // TODO unit test for the property 'SecureAccessBastionIssuer'
        }
        /// <summary>
        /// Test the property 'SecureAccessDbSchema'
        /// </summary>
        [Fact]
        public void SecureAccessDbSchemaTest()
        {
            // TODO unit test for the property 'SecureAccessDbSchema'
        }
        /// <summary>
        /// Test the property 'SecureAccessEnable'
        /// </summary>
        [Fact]
        public void SecureAccessEnableTest()
        {
            // TODO unit test for the property 'SecureAccessEnable'
        }
        /// <summary>
        /// Test the property 'SecureAccessHost'
        /// </summary>
        [Fact]
        public void SecureAccessHostTest()
        {
            // TODO unit test for the property 'SecureAccessHost'
        }
        /// <summary>
        /// Test the property 'SecureAccessWeb'
        /// </summary>
        [Fact]
        public void SecureAccessWebTest()
        {
            // TODO unit test for the property 'SecureAccessWeb'
        }
        /// <summary>
        /// Test the property 'Ssl'
        /// </summary>
        [Fact]
        public void SslTest()
        {
            // TODO unit test for the property 'Ssl'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'TargetName'
        /// </summary>
        [Fact]
        public void TargetNameTest()
        {
            // TODO unit test for the property 'TargetName'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }
        /// <summary>
        /// Test the property 'UserTtl'
        /// </summary>
        [Fact]
        public void UserTtlTest()
        {
            // TODO unit test for the property 'UserTtl'
        }

    }

}
