/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing DynamicSecretUpdateRedis
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DynamicSecretUpdateRedisTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DynamicSecretUpdateRedis
        //private DynamicSecretUpdateRedis instance;

        public DynamicSecretUpdateRedisTests()
        {
            // TODO uncomment below to create an instance of DynamicSecretUpdateRedis
            //instance = new DynamicSecretUpdateRedis();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DynamicSecretUpdateRedis
        /// </summary>
        [Fact]
        public void DynamicSecretUpdateRedisInstanceTest()
        {
            // TODO uncomment below to test "IsType" DynamicSecretUpdateRedis
            //Assert.IsType<DynamicSecretUpdateRedis>(instance);
        }


        /// <summary>
        /// Test the property 'AclRules'
        /// </summary>
        [Fact]
        public void AclRulesTest()
        {
            // TODO unit test for the property 'AclRules'
        }
        /// <summary>
        /// Test the property 'DeleteProtection'
        /// </summary>
        [Fact]
        public void DeleteProtectionTest()
        {
            // TODO unit test for the property 'DeleteProtection'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NewName'
        /// </summary>
        [Fact]
        public void NewNameTest()
        {
            // TODO unit test for the property 'NewName'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'PasswordLength'
        /// </summary>
        [Fact]
        public void PasswordLengthTest()
        {
            // TODO unit test for the property 'PasswordLength'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'ProducerEncryptionKeyName'
        /// </summary>
        [Fact]
        public void ProducerEncryptionKeyNameTest()
        {
            // TODO unit test for the property 'ProducerEncryptionKeyName'
        }
        /// <summary>
        /// Test the property 'Ssl'
        /// </summary>
        [Fact]
        public void SslTest()
        {
            // TODO unit test for the property 'Ssl'
        }
        /// <summary>
        /// Test the property 'SslCertificate'
        /// </summary>
        [Fact]
        public void SslCertificateTest()
        {
            // TODO unit test for the property 'SslCertificate'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'TargetName'
        /// </summary>
        [Fact]
        public void TargetNameTest()
        {
            // TODO unit test for the property 'TargetName'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }
        /// <summary>
        /// Test the property 'UserTtl'
        /// </summary>
        [Fact]
        public void UserTtlTest()
        {
            // TODO unit test for the property 'UserTtl'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
