/* 
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test
{
    /// <summary>
    ///  Class for testing GatewayCreateProducerMSSQLOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayCreateProducerMSSQLOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayCreateProducerMSSQLOutput
        //private GatewayCreateProducerMSSQLOutput instance;

        public GatewayCreateProducerMSSQLOutputTests()
        {
            // TODO uncomment below to create an instance of GatewayCreateProducerMSSQLOutput
            //instance = new GatewayCreateProducerMSSQLOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayCreateProducerMSSQLOutput
        /// </summary>
        [Fact]
        public void GatewayCreateProducerMSSQLOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GatewayCreateProducerMSSQLOutput
            //Assert.IsInstanceOfType<GatewayCreateProducerMSSQLOutput> (instance, "variable 'instance' is a GatewayCreateProducerMSSQLOutput");
        }


        /// <summary>
        /// Test the property 'ProducerDetails'
        /// </summary>
        [Fact]
        public void ProducerDetailsTest()
        {
            // TODO unit test for the property 'ProducerDetails'
        }

    }

}
