/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing GatewayGetRemoteAccess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayGetRemoteAccessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayGetRemoteAccess
        //private GatewayGetRemoteAccess instance;

        public GatewayGetRemoteAccessTests()
        {
            // TODO uncomment below to create an instance of GatewayGetRemoteAccess
            //instance = new GatewayGetRemoteAccess();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayGetRemoteAccess
        /// </summary>
        [Fact]
        public void GatewayGetRemoteAccessInstanceTest()
        {
            // TODO uncomment below to test "IsType" GatewayGetRemoteAccess
            //Assert.IsType<GatewayGetRemoteAccess>(instance);
        }


        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }

    }

}
