/* 
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test
{
    /// <summary>
    ///  Class for testing GatewayUpdateProducerCustomOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayUpdateProducerCustomOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayUpdateProducerCustomOutput
        //private GatewayUpdateProducerCustomOutput instance;

        public GatewayUpdateProducerCustomOutputTests()
        {
            // TODO uncomment below to create an instance of GatewayUpdateProducerCustomOutput
            //instance = new GatewayUpdateProducerCustomOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayUpdateProducerCustomOutput
        /// </summary>
        [Fact]
        public void GatewayUpdateProducerCustomOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GatewayUpdateProducerCustomOutput
            //Assert.IsInstanceOfType<GatewayUpdateProducerCustomOutput> (instance, "variable 'instance' is a GatewayUpdateProducerCustomOutput");
        }


        /// <summary>
        /// Test the property 'ProducerDetails'
        /// </summary>
        [Fact]
        public void ProducerDetailsTest()
        {
            // TODO unit test for the property 'ProducerDetails'
        }

    }

}
