/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing GetLastUserEventStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetLastUserEventStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetLastUserEventStatus
        //private GetLastUserEventStatus instance;

        public GetLastUserEventStatusTests()
        {
            // TODO uncomment below to create an instance of GetLastUserEventStatus
            //instance = new GetLastUserEventStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetLastUserEventStatus
        /// </summary>
        [Fact]
        public void GetLastUserEventStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetLastUserEventStatus
            //Assert.IsType<GetLastUserEventStatus>(instance);
        }


        /// <summary>
        /// Test the property 'EventSource'
        /// </summary>
        [Fact]
        public void EventSourceTest()
        {
            // TODO unit test for the property 'EventSource'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'ItemName'
        /// </summary>
        [Fact]
        public void ItemNameTest()
        {
            // TODO unit test for the property 'ItemName'
        }
        /// <summary>
        /// Test the property 'ItemType'
        /// </summary>
        [Fact]
        public void ItemTypeTest()
        {
            // TODO unit test for the property 'ItemType'
        }
        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
        /// <summary>
        /// Test the property 'TimeBack'
        /// </summary>
        [Fact]
        public void TimeBackTest()
        {
            // TODO unit test for the property 'TimeBack'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }

    }

}
