/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing GoogleChronicleForwardingConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoogleChronicleForwardingConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoogleChronicleForwardingConfig
        //private GoogleChronicleForwardingConfig instance;

        public GoogleChronicleForwardingConfigTests()
        {
            // TODO uncomment below to create an instance of GoogleChronicleForwardingConfig
            //instance = new GoogleChronicleForwardingConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoogleChronicleForwardingConfig
        /// </summary>
        [Fact]
        public void GoogleChronicleForwardingConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoogleChronicleForwardingConfig
            //Assert.IsType<GoogleChronicleForwardingConfig>(instance);
        }


        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'LogType'
        /// </summary>
        [Fact]
        public void LogTypeTest()
        {
            // TODO unit test for the property 'LogType'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'ServiceAccountKey'
        /// </summary>
        [Fact]
        public void ServiceAccountKeyTest()
        {
            // TODO unit test for the property 'ServiceAccountKey'
        }

    }

}
