/* 
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test
{
    /// <summary>
    ///  Class for testing KMIPClientsConfigPart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KMIPClientsConfigPartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KMIPClientsConfigPart
        //private KMIPClientsConfigPart instance;

        public KMIPClientsConfigPartTests()
        {
            // TODO uncomment below to create an instance of KMIPClientsConfigPart
            //instance = new KMIPClientsConfigPart();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KMIPClientsConfigPart
        /// </summary>
        [Fact]
        public void KMIPClientsConfigPartInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KMIPClientsConfigPart
            //Assert.IsInstanceOfType<KMIPClientsConfigPart> (instance, "variable 'instance' is a KMIPClientsConfigPart");
        }


        /// <summary>
        /// Test the property 'Clients'
        /// </summary>
        [Fact]
        public void ClientsTest()
        {
            // TODO unit test for the property 'Clients'
        }

    }

}
