/* 
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test
{
    /// <summary>
    ///  Class for testing LeadershipConfigPart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LeadershipConfigPartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LeadershipConfigPart
        //private LeadershipConfigPart instance;

        public LeadershipConfigPartTests()
        {
            // TODO uncomment below to create an instance of LeadershipConfigPart
            //instance = new LeadershipConfigPart();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeadershipConfigPart
        /// </summary>
        [Fact]
        public void LeadershipConfigPartInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeadershipConfigPart
            //Assert.IsInstanceOfType<LeadershipConfigPart> (instance, "variable 'instance' is a LeadershipConfigPart");
        }


        /// <summary>
        /// Test the property 'OpenLeadership'
        /// </summary>
        [Fact]
        public void OpenLeadershipTest()
        {
            // TODO unit test for the property 'OpenLeadership'
        }

    }

}
