/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing PoliciesListOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PoliciesListOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PoliciesListOutput
        //private PoliciesListOutput instance;

        public PoliciesListOutputTests()
        {
            // TODO uncomment below to create an instance of PoliciesListOutput
            //instance = new PoliciesListOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PoliciesListOutput
        /// </summary>
        [Fact]
        public void PoliciesListOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" PoliciesListOutput
            //Assert.IsType<PoliciesListOutput>(instance);
        }

        /// <summary>
        /// Test the property 'Policies'
        /// </summary>
        [Fact]
        public void PoliciesTest()
        {
            // TODO unit test for the property 'Policies'
        }
    }
}
