/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing RotatedSecretCreateGcp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RotatedSecretCreateGcpTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RotatedSecretCreateGcp
        //private RotatedSecretCreateGcp instance;

        public RotatedSecretCreateGcpTests()
        {
            // TODO uncomment below to create an instance of RotatedSecretCreateGcp
            //instance = new RotatedSecretCreateGcp();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RotatedSecretCreateGcp
        /// </summary>
        [Fact]
        public void RotatedSecretCreateGcpInstanceTest()
        {
            // TODO uncomment below to test "IsType" RotatedSecretCreateGcp
            //Assert.IsType<RotatedSecretCreateGcp>(instance);
        }


        /// <summary>
        /// Test the property 'AuthenticationCredentials'
        /// </summary>
        [Fact]
        public void AuthenticationCredentialsTest()
        {
            // TODO unit test for the property 'AuthenticationCredentials'
        }
        /// <summary>
        /// Test the property 'AutoRotate'
        /// </summary>
        [Fact]
        public void AutoRotateTest()
        {
            // TODO unit test for the property 'AutoRotate'
        }
        /// <summary>
        /// Test the property 'DeleteProtection'
        /// </summary>
        [Fact]
        public void DeleteProtectionTest()
        {
            // TODO unit test for the property 'DeleteProtection'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'GcpKey'
        /// </summary>
        [Fact]
        public void GcpKeyTest()
        {
            // TODO unit test for the property 'GcpKey'
        }
        /// <summary>
        /// Test the property 'GcpServiceAccountEmail'
        /// </summary>
        [Fact]
        public void GcpServiceAccountEmailTest()
        {
            // TODO unit test for the property 'GcpServiceAccountEmail'
        }
        /// <summary>
        /// Test the property 'GcpServiceAccountKeyId'
        /// </summary>
        [Fact]
        public void GcpServiceAccountKeyIdTest()
        {
            // TODO unit test for the property 'GcpServiceAccountKeyId'
        }
        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PasswordLength'
        /// </summary>
        [Fact]
        public void PasswordLengthTest()
        {
            // TODO unit test for the property 'PasswordLength'
        }
        /// <summary>
        /// Test the property 'RotationHour'
        /// </summary>
        [Fact]
        public void RotationHourTest()
        {
            // TODO unit test for the property 'RotationHour'
        }
        /// <summary>
        /// Test the property 'RotationInterval'
        /// </summary>
        [Fact]
        public void RotationIntervalTest()
        {
            // TODO unit test for the property 'RotationInterval'
        }
        /// <summary>
        /// Test the property 'RotatorType'
        /// </summary>
        [Fact]
        public void RotatorTypeTest()
        {
            // TODO unit test for the property 'RotatorType'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'TargetName'
        /// </summary>
        [Fact]
        public void TargetNameTest()
        {
            // TODO unit test for the property 'TargetName'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }

    }

}
