/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing TargetUpdateGke
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TargetUpdateGkeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TargetUpdateGke
        //private TargetUpdateGke instance;

        public TargetUpdateGkeTests()
        {
            // TODO uncomment below to create an instance of TargetUpdateGke
            //instance = new TargetUpdateGke();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TargetUpdateGke
        /// </summary>
        [Fact]
        public void TargetUpdateGkeInstanceTest()
        {
            // TODO uncomment below to test "IsType" TargetUpdateGke
            //Assert.IsType<TargetUpdateGke>(instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'GkeAccountKey'
        /// </summary>
        [Fact]
        public void GkeAccountKeyTest()
        {
            // TODO unit test for the property 'GkeAccountKey'
        }
        /// <summary>
        /// Test the property 'GkeClusterCert'
        /// </summary>
        [Fact]
        public void GkeClusterCertTest()
        {
            // TODO unit test for the property 'GkeClusterCert'
        }
        /// <summary>
        /// Test the property 'GkeClusterEndpoint'
        /// </summary>
        [Fact]
        public void GkeClusterEndpointTest()
        {
            // TODO unit test for the property 'GkeClusterEndpoint'
        }
        /// <summary>
        /// Test the property 'GkeClusterName'
        /// </summary>
        [Fact]
        public void GkeClusterNameTest()
        {
            // TODO unit test for the property 'GkeClusterName'
        }
        /// <summary>
        /// Test the property 'GkeServiceAccountEmail'
        /// </summary>
        [Fact]
        public void GkeServiceAccountEmailTest()
        {
            // TODO unit test for the property 'GkeServiceAccountEmail'
        }
        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
        /// <summary>
        /// Test the property 'KeepPrevVersion'
        /// </summary>
        [Fact]
        public void KeepPrevVersionTest()
        {
            // TODO unit test for the property 'KeepPrevVersion'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'MaxVersions'
        /// </summary>
        [Fact]
        public void MaxVersionsTest()
        {
            // TODO unit test for the property 'MaxVersions'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NewName'
        /// </summary>
        [Fact]
        public void NewNameTest()
        {
            // TODO unit test for the property 'NewName'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }
        /// <summary>
        /// Test the property 'UseGwCloudIdentity'
        /// </summary>
        [Fact]
        public void UseGwCloudIdentityTest()
        {
            // TODO unit test for the property 'UseGwCloudIdentity'
        }

    }

}
