/* 
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test
{
    /// <summary>
    ///  Class for testing UpdateRabbitMQTargetDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRabbitMQTargetDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateRabbitMQTargetDetails
        //private UpdateRabbitMQTargetDetails instance;

        public UpdateRabbitMQTargetDetailsTests()
        {
            // TODO uncomment below to create an instance of UpdateRabbitMQTargetDetails
            //instance = new UpdateRabbitMQTargetDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateRabbitMQTargetDetails
        /// </summary>
        [Fact]
        public void UpdateRabbitMQTargetDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateRabbitMQTargetDetails
            //Assert.IsInstanceOfType<UpdateRabbitMQTargetDetails> (instance, "variable 'instance' is a UpdateRabbitMQTargetDetails");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProtectionKey'
        /// </summary>
        [Fact]
        public void ProtectionKeyTest()
        {
            // TODO unit test for the property 'ProtectionKey'
        }
        /// <summary>
        /// Test the property 'RabbitmqServerPassword'
        /// </summary>
        [Fact]
        public void RabbitmqServerPasswordTest()
        {
            // TODO unit test for the property 'RabbitmqServerPassword'
        }
        /// <summary>
        /// Test the property 'RabbitmqServerUri'
        /// </summary>
        [Fact]
        public void RabbitmqServerUriTest()
        {
            // TODO unit test for the property 'RabbitmqServerUri'
        }
        /// <summary>
        /// Test the property 'RabbitmqServerUser'
        /// </summary>
        [Fact]
        public void RabbitmqServerUserTest()
        {
            // TODO unit test for the property 'RabbitmqServerUser'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UidToken'
        /// </summary>
        [Fact]
        public void UidTokenTest()
        {
            // TODO unit test for the property 'UidToken'
        }

    }

}
