/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateGitlabTargetOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateGitlabTargetOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateGitlabTargetOutput
        //private UpdateGitlabTargetOutput instance;

        public UpdateGitlabTargetOutputTests()
        {
            // TODO uncomment below to create an instance of UpdateGitlabTargetOutput
            //instance = new UpdateGitlabTargetOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateGitlabTargetOutput
        /// </summary>
        [Fact]
        public void UpdateGitlabTargetOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateGitlabTargetOutput
            //Assert.IsType<UpdateGitlabTargetOutput>(instance);
        }


        /// <summary>
        /// Test the property 'TargetId'
        /// </summary>
        [Fact]
        public void TargetIdTest()
        {
            // TODO unit test for the property 'TargetId'
        }

    }

}
