/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateAccountSettingsOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAccountSettingsOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateAccountSettingsOutput
        //private UpdateAccountSettingsOutput instance;

        public UpdateAccountSettingsOutputTests()
        {
            // TODO uncomment below to create an instance of UpdateAccountSettingsOutput
            //instance = new UpdateAccountSettingsOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateAccountSettingsOutput
        /// </summary>
        [Fact]
        public void UpdateAccountSettingsOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateAccountSettingsOutput
            //Assert.IsType<UpdateAccountSettingsOutput>(instance);
        }


        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

    }

}
