/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Api;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing UscUpdateSecretOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UscUpdateSecretOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UscUpdateSecretOutput
        //private UscUpdateSecretOutput instance;

        public UscUpdateSecretOutputTests()
        {
            // TODO uncomment below to create an instance of UscUpdateSecretOutput
            //instance = new UscUpdateSecretOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UscUpdateSecretOutput
        /// </summary>
        [Fact]
        public void UscUpdateSecretOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" UscUpdateSecretOutput
            //Assert.IsType<UscUpdateSecretOutput>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SecretId'
        /// </summary>
        [Fact]
        public void SecretIdTest()
        {
            // TODO unit test for the property 'SecretId'
        }
        /// <summary>
        /// Test the property 'VersionId'
        /// </summary>
        [Fact]
        public void VersionIdTest()
        {
            // TODO unit test for the property 'VersionId'
        }

    }

}
