/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using akeyless.Model;
using akeyless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace akeyless.Test.Model
{
    /// <summary>
    ///  Class for testing VaultAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VaultAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VaultAddress
        //private VaultAddress instance;

        public VaultAddressTests()
        {
            // TODO uncomment below to create an instance of VaultAddress
            //instance = new VaultAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VaultAddress
        /// </summary>
        [Fact]
        public void VaultAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" VaultAddress
            //Assert.IsType<VaultAddress>(instance);
        }

        /// <summary>
        /// Test the property 'AccessId'
        /// </summary>
        [Fact]
        public void AccessIdTest()
        {
            // TODO unit test for the property 'AccessId'
        }

        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
    }
}
