/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// CertificateChainInfo
    /// </summary>
    [DataContract(Name = "CertificateChainInfo")]
    public partial class CertificateChainInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CertificateChainInfo" /> class.
        /// </summary>
        /// <param name="autoRenewCertificate">autoRenewCertificate.</param>
        /// <param name="certificateChain">certificateChain.</param>
        /// <param name="certificateFormat">certificateFormat.</param>
        /// <param name="certificateHasPrivateKey">certificateHasPrivateKey.</param>
        /// <param name="certificateIssuerGwClusterId">certificateIssuerGwClusterId.</param>
        /// <param name="certificateIssuerGwClusterUrl">certificateIssuerGwClusterUrl.</param>
        /// <param name="certificateIssuerItemId">certificateIssuerItemId.</param>
        /// <param name="certificateIssuerName">certificateIssuerName.</param>
        /// <param name="certificatePem">certificatePem.</param>
        /// <param name="certificateStatus">certificateStatus.</param>
        /// <param name="commonName">commonName.</param>
        /// <param name="errorMessage">errorMessage.</param>
        /// <param name="expirationDate">expirationDate.</param>
        /// <param name="expirationEvents">expirationEvents.</param>
        /// <param name="externalCaId">externalCaId.</param>
        /// <param name="issuanceStatus">issuanceStatus.</param>
        /// <param name="notBefore">notBefore.</param>
        /// <param name="renewBeforeExpirationInDays">renewBeforeExpirationInDays.</param>
        public CertificateChainInfo(bool autoRenewCertificate = default(bool), List<CertificateInfo> certificateChain = default(List<CertificateInfo>), string certificateFormat = default(string), bool certificateHasPrivateKey = default(bool), long certificateIssuerGwClusterId = default(long), string certificateIssuerGwClusterUrl = default(string), long certificateIssuerItemId = default(long), string certificateIssuerName = default(string), string certificatePem = default(string), string certificateStatus = default(string), string commonName = default(string), string errorMessage = default(string), DateTime expirationDate = default(DateTime), List<CertificateExpirationEvent> expirationEvents = default(List<CertificateExpirationEvent>), NullString externalCaId = default(NullString), string issuanceStatus = default(string), DateTime notBefore = default(DateTime), long renewBeforeExpirationInDays = default(long))
        {
            this.AutoRenewCertificate = autoRenewCertificate;
            this.CertificateChain = certificateChain;
            this.CertificateFormat = certificateFormat;
            this.CertificateHasPrivateKey = certificateHasPrivateKey;
            this.CertificateIssuerGwClusterId = certificateIssuerGwClusterId;
            this.CertificateIssuerGwClusterUrl = certificateIssuerGwClusterUrl;
            this.CertificateIssuerItemId = certificateIssuerItemId;
            this.CertificateIssuerName = certificateIssuerName;
            this.CertificatePem = certificatePem;
            this.CertificateStatus = certificateStatus;
            this.CommonName = commonName;
            this.ErrorMessage = errorMessage;
            this.ExpirationDate = expirationDate;
            this.ExpirationEvents = expirationEvents;
            this.ExternalCaId = externalCaId;
            this.IssuanceStatus = issuanceStatus;
            this.NotBefore = notBefore;
            this.RenewBeforeExpirationInDays = renewBeforeExpirationInDays;
        }

        /// <summary>
        /// Gets or Sets AutoRenewCertificate
        /// </summary>
        [DataMember(Name = "auto_renew_certificate", EmitDefaultValue = true)]
        public bool AutoRenewCertificate { get; set; }

        /// <summary>
        /// Gets or Sets CertificateChain
        /// </summary>
        [DataMember(Name = "certificate_chain", EmitDefaultValue = false)]
        public List<CertificateInfo> CertificateChain { get; set; }

        /// <summary>
        /// Gets or Sets CertificateFormat
        /// </summary>
        [DataMember(Name = "certificate_format", EmitDefaultValue = false)]
        public string CertificateFormat { get; set; }

        /// <summary>
        /// Gets or Sets CertificateHasPrivateKey
        /// </summary>
        [DataMember(Name = "certificate_has_private_key", EmitDefaultValue = true)]
        public bool CertificateHasPrivateKey { get; set; }

        /// <summary>
        /// Gets or Sets CertificateIssuerGwClusterId
        /// </summary>
        [DataMember(Name = "certificate_issuer_gw_cluster_id", EmitDefaultValue = false)]
        public long CertificateIssuerGwClusterId { get; set; }

        /// <summary>
        /// Gets or Sets CertificateIssuerGwClusterUrl
        /// </summary>
        [DataMember(Name = "certificate_issuer_gw_cluster_url", EmitDefaultValue = false)]
        public string CertificateIssuerGwClusterUrl { get; set; }

        /// <summary>
        /// Gets or Sets CertificateIssuerItemId
        /// </summary>
        [DataMember(Name = "certificate_issuer_item_id", EmitDefaultValue = false)]
        public long CertificateIssuerItemId { get; set; }

        /// <summary>
        /// Gets or Sets CertificateIssuerName
        /// </summary>
        [DataMember(Name = "certificate_issuer_name", EmitDefaultValue = false)]
        public string CertificateIssuerName { get; set; }

        /// <summary>
        /// Gets or Sets CertificatePem
        /// </summary>
        [DataMember(Name = "certificate_pem", EmitDefaultValue = false)]
        public string CertificatePem { get; set; }

        /// <summary>
        /// Gets or Sets CertificateStatus
        /// </summary>
        [DataMember(Name = "certificate_status", EmitDefaultValue = false)]
        public string CertificateStatus { get; set; }

        /// <summary>
        /// Gets or Sets CommonName
        /// </summary>
        [DataMember(Name = "common_name", EmitDefaultValue = false)]
        public string CommonName { get; set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [DataMember(Name = "error_message", EmitDefaultValue = false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationDate
        /// </summary>
        [DataMember(Name = "expiration_date", EmitDefaultValue = false)]
        public DateTime ExpirationDate { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationEvents
        /// </summary>
        [DataMember(Name = "expiration_events", EmitDefaultValue = false)]
        public List<CertificateExpirationEvent> ExpirationEvents { get; set; }

        /// <summary>
        /// Gets or Sets ExternalCaId
        /// </summary>
        [DataMember(Name = "external_ca_id", EmitDefaultValue = false)]
        public NullString ExternalCaId { get; set; }

        /// <summary>
        /// Gets or Sets IssuanceStatus
        /// </summary>
        [DataMember(Name = "issuance_status", EmitDefaultValue = false)]
        public string IssuanceStatus { get; set; }

        /// <summary>
        /// Gets or Sets NotBefore
        /// </summary>
        [DataMember(Name = "not_before", EmitDefaultValue = false)]
        public DateTime NotBefore { get; set; }

        /// <summary>
        /// Gets or Sets RenewBeforeExpirationInDays
        /// </summary>
        [DataMember(Name = "renew_before_expiration_in_days", EmitDefaultValue = false)]
        public long RenewBeforeExpirationInDays { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CertificateChainInfo {\n");
            sb.Append("  AutoRenewCertificate: ").Append(AutoRenewCertificate).Append("\n");
            sb.Append("  CertificateChain: ").Append(CertificateChain).Append("\n");
            sb.Append("  CertificateFormat: ").Append(CertificateFormat).Append("\n");
            sb.Append("  CertificateHasPrivateKey: ").Append(CertificateHasPrivateKey).Append("\n");
            sb.Append("  CertificateIssuerGwClusterId: ").Append(CertificateIssuerGwClusterId).Append("\n");
            sb.Append("  CertificateIssuerGwClusterUrl: ").Append(CertificateIssuerGwClusterUrl).Append("\n");
            sb.Append("  CertificateIssuerItemId: ").Append(CertificateIssuerItemId).Append("\n");
            sb.Append("  CertificateIssuerName: ").Append(CertificateIssuerName).Append("\n");
            sb.Append("  CertificatePem: ").Append(CertificatePem).Append("\n");
            sb.Append("  CertificateStatus: ").Append(CertificateStatus).Append("\n");
            sb.Append("  CommonName: ").Append(CommonName).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  ExpirationEvents: ").Append(ExpirationEvents).Append("\n");
            sb.Append("  ExternalCaId: ").Append(ExternalCaId).Append("\n");
            sb.Append("  IssuanceStatus: ").Append(IssuanceStatus).Append("\n");
            sb.Append("  NotBefore: ").Append(NotBefore).Append("\n");
            sb.Append("  RenewBeforeExpirationInDays: ").Append(RenewBeforeExpirationInDays).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
