/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// CustomerFragmentConfig
    /// </summary>
    [DataContract(Name = "CustomerFragmentConfig")]
    public partial class CustomerFragmentConfig : IEquatable<CustomerFragmentConfig>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerFragmentConfig" /> class.
        /// </summary>
        /// <param name="description">description.</param>
        /// <param name="fragmentType">fragmentType.</param>
        /// <param name="id">id.</param>
        /// <param name="keyLabel">keyLabel.</param>
        /// <param name="name">name.</param>
        /// <param name="value">value.</param>
        public CustomerFragmentConfig(string description = default(string), string fragmentType = default(string), string id = default(string), string keyLabel = default(string), string name = default(string), string value = default(string))
        {
            this.Description = description;
            this.FragmentType = fragmentType;
            this.Id = id;
            this.KeyLabel = keyLabel;
            this.Name = name;
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets FragmentType
        /// </summary>
        [DataMember(Name = "fragment_type", EmitDefaultValue = false)]
        public string FragmentType { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets KeyLabel
        /// </summary>
        [DataMember(Name = "key_label", EmitDefaultValue = false)]
        public string KeyLabel { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomerFragmentConfig {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  FragmentType: ").Append(FragmentType).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  KeyLabel: ").Append(KeyLabel).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CustomerFragmentConfig);
        }

        /// <summary>
        /// Returns true if CustomerFragmentConfig instances are equal
        /// </summary>
        /// <param name="input">Instance of CustomerFragmentConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomerFragmentConfig input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.FragmentType == input.FragmentType ||
                    (this.FragmentType != null &&
                    this.FragmentType.Equals(input.FragmentType))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.KeyLabel == input.KeyLabel ||
                    (this.KeyLabel != null &&
                    this.KeyLabel.Equals(input.KeyLabel))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.FragmentType != null)
                {
                    hashCode = (hashCode * 59) + this.FragmentType.GetHashCode();
                }
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.KeyLabel != null)
                {
                    hashCode = (hashCode * 59) + this.KeyLabel.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
