/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// dynamicSecretTmpCredsDelete is a command that deletes dynamic secret temp creds
    /// </summary>
    [DataContract(Name = "dynamicSecretTmpCredsDelete")]
    public partial class DynamicSecretTmpCredsDelete : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DynamicSecretTmpCredsDelete" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DynamicSecretTmpCredsDelete() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DynamicSecretTmpCredsDelete" /> class.
        /// </summary>
        /// <param name="host">Host.</param>
        /// <param name="json">Set output format to JSON (default to false).</param>
        /// <param name="name">Dynamic secret name (required).</param>
        /// <param name="revokeAll">Revoke All Temp Creds.</param>
        /// <param name="softDelete">Soft Delete.</param>
        /// <param name="tmpCredsId">Tmp Creds ID.</param>
        /// <param name="token">Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;).</param>
        /// <param name="uidToken">The universal identity token, Required only for universal_identity authentication.</param>
        public DynamicSecretTmpCredsDelete(string host = default(string), bool json = false, string name = default(string), bool revokeAll = default(bool), bool softDelete = default(bool), string tmpCredsId = default(string), string token = default(string), string uidToken = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for DynamicSecretTmpCredsDelete and cannot be null");
            }
            this.Name = name;
            this.Host = host;
            this.Json = json;
            this.RevokeAll = revokeAll;
            this.SoftDelete = softDelete;
            this.TmpCredsId = tmpCredsId;
            this.Token = token;
            this.UidToken = uidToken;
        }

        /// <summary>
        /// Host
        /// </summary>
        /// <value>Host</value>
        [DataMember(Name = "host", EmitDefaultValue = false)]
        public string Host { get; set; }

        /// <summary>
        /// Set output format to JSON
        /// </summary>
        /// <value>Set output format to JSON</value>
        [DataMember(Name = "json", EmitDefaultValue = true)]
        public bool Json { get; set; }

        /// <summary>
        /// Dynamic secret name
        /// </summary>
        /// <value>Dynamic secret name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Revoke All Temp Creds
        /// </summary>
        /// <value>Revoke All Temp Creds</value>
        [DataMember(Name = "revoke-all", EmitDefaultValue = true)]
        public bool RevokeAll { get; set; }

        /// <summary>
        /// Soft Delete
        /// </summary>
        /// <value>Soft Delete</value>
        [DataMember(Name = "soft-delete", EmitDefaultValue = true)]
        public bool SoftDelete { get; set; }

        /// <summary>
        /// Tmp Creds ID
        /// </summary>
        /// <value>Tmp Creds ID</value>
        [DataMember(Name = "tmp-creds-id", EmitDefaultValue = false)]
        public string TmpCredsId { get; set; }

        /// <summary>
        /// Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)
        /// </summary>
        /// <value>Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)</value>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public string Token { get; set; }

        /// <summary>
        /// The universal identity token, Required only for universal_identity authentication
        /// </summary>
        /// <value>The universal identity token, Required only for universal_identity authentication</value>
        [DataMember(Name = "uid-token", EmitDefaultValue = false)]
        public string UidToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DynamicSecretTmpCredsDelete {\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("  Json: ").Append(Json).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RevokeAll: ").Append(RevokeAll).Append("\n");
            sb.Append("  SoftDelete: ").Append(SoftDelete).Append("\n");
            sb.Append("  TmpCredsId: ").Append(TmpCredsId).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  UidToken: ").Append(UidToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
