/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// esmGet is a command that gets the value and interal details of a secret from an External Secrets Manager
    /// </summary>
    [DataContract(Name = "esmGet")]
    public partial class EsmGet : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsmGet" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EsmGet() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EsmGet" /> class.
        /// </summary>
        /// <param name="esmName">Name of the External Secrets Manager item (required).</param>
        /// <param name="json">Set output format to JSON (default to false).</param>
        /// <param name="secretId">The secret id (or name, for AWS, Azure or K8s targets) to get from the External Secrets Manager (required).</param>
        /// <param name="token">Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;).</param>
        /// <param name="uidToken">The universal identity token, Required only for universal_identity authentication.</param>
        public EsmGet(string esmName = default(string), bool json = false, string secretId = default(string), string token = default(string), string uidToken = default(string))
        {
            // to ensure "esmName" is required (not null)
            if (esmName == null)
            {
                throw new ArgumentNullException("esmName is a required property for EsmGet and cannot be null");
            }
            this.EsmName = esmName;
            // to ensure "secretId" is required (not null)
            if (secretId == null)
            {
                throw new ArgumentNullException("secretId is a required property for EsmGet and cannot be null");
            }
            this.SecretId = secretId;
            this.Json = json;
            this.Token = token;
            this.UidToken = uidToken;
        }

        /// <summary>
        /// Name of the External Secrets Manager item
        /// </summary>
        /// <value>Name of the External Secrets Manager item</value>
        [DataMember(Name = "esm-name", IsRequired = true, EmitDefaultValue = true)]
        public string EsmName { get; set; }

        /// <summary>
        /// Set output format to JSON
        /// </summary>
        /// <value>Set output format to JSON</value>
        [DataMember(Name = "json", EmitDefaultValue = true)]
        public bool Json { get; set; }

        /// <summary>
        /// The secret id (or name, for AWS, Azure or K8s targets) to get from the External Secrets Manager
        /// </summary>
        /// <value>The secret id (or name, for AWS, Azure or K8s targets) to get from the External Secrets Manager</value>
        [DataMember(Name = "secret-id", IsRequired = true, EmitDefaultValue = true)]
        public string SecretId { get; set; }

        /// <summary>
        /// Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)
        /// </summary>
        /// <value>Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)</value>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public string Token { get; set; }

        /// <summary>
        /// The universal identity token, Required only for universal_identity authentication
        /// </summary>
        /// <value>The universal identity token, Required only for universal_identity authentication</value>
        [DataMember(Name = "uid-token", EmitDefaultValue = false)]
        public string UidToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsmGet {\n");
            sb.Append("  EsmName: ").Append(EsmName).Append("\n");
            sb.Append("  Json: ").Append(Json).Append("\n");
            sb.Append("  SecretId: ").Append(SecretId).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  UidToken: ").Append(UidToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
