/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// gatewayCreateProducerGithub is a command that creates github producer
    /// </summary>
    [DataContract(Name = "gatewayCreateProducerGithub")]
    public partial class GatewayCreateProducerGithub : IEquatable<GatewayCreateProducerGithub>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GatewayCreateProducerGithub" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GatewayCreateProducerGithub() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GatewayCreateProducerGithub" /> class.
        /// </summary>
        /// <param name="deleteProtection">Protection from accidental deletion of this item.</param>
        /// <param name="githubAppId">Github app id.</param>
        /// <param name="githubAppPrivateKey">App private key.</param>
        /// <param name="githubBaseUrl">Base URL.</param>
        /// <param name="installationId">Github app installation id.</param>
        /// <param name="installationRepository">Repository that the app installation has access to.</param>
        /// <param name="json">Set output format to JSON.</param>
        /// <param name="name">Producer name (required).</param>
        /// <param name="targetName">Target name.</param>
        /// <param name="token">Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;).</param>
        /// <param name="tokenPermissions">Optional - installation token&#39;s allowed permissions.</param>
        /// <param name="tokenRepositories">Optional - installation token&#39;s allowed repositories.</param>
        /// <param name="uidToken">The universal identity token, Required only for universal_identity authentication.</param>
        public GatewayCreateProducerGithub(string deleteProtection = default(string), long githubAppId = default(long), string githubAppPrivateKey = default(string), string githubBaseUrl = default(string), long installationId = default(long), string installationRepository = default(string), bool json = default(bool), string name = default(string), string targetName = default(string), string token = default(string), List<string> tokenPermissions = default(List<string>), List<string> tokenRepositories = default(List<string>), string uidToken = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for GatewayCreateProducerGithub and cannot be null");
            }
            this.Name = name;
            this.DeleteProtection = deleteProtection;
            this.GithubAppId = githubAppId;
            this.GithubAppPrivateKey = githubAppPrivateKey;
            this.GithubBaseUrl = githubBaseUrl;
            this.InstallationId = installationId;
            this.InstallationRepository = installationRepository;
            this.Json = json;
            this.TargetName = targetName;
            this.Token = token;
            this.TokenPermissions = tokenPermissions;
            this.TokenRepositories = tokenRepositories;
            this.UidToken = uidToken;
        }

        /// <summary>
        /// Protection from accidental deletion of this item
        /// </summary>
        /// <value>Protection from accidental deletion of this item</value>
        [DataMember(Name = "delete_protection", EmitDefaultValue = false)]
        public string DeleteProtection { get; set; }

        /// <summary>
        /// Github app id
        /// </summary>
        /// <value>Github app id</value>
        [DataMember(Name = "github-app-id", EmitDefaultValue = false)]
        public long GithubAppId { get; set; }

        /// <summary>
        /// App private key
        /// </summary>
        /// <value>App private key</value>
        [DataMember(Name = "github-app-private-key", EmitDefaultValue = false)]
        public string GithubAppPrivateKey { get; set; }

        /// <summary>
        /// Base URL
        /// </summary>
        /// <value>Base URL</value>
        [DataMember(Name = "github-base-url", EmitDefaultValue = false)]
        public string GithubBaseUrl { get; set; }

        /// <summary>
        /// Github app installation id
        /// </summary>
        /// <value>Github app installation id</value>
        [DataMember(Name = "installation-id", EmitDefaultValue = false)]
        public long InstallationId { get; set; }

        /// <summary>
        /// Repository that the app installation has access to
        /// </summary>
        /// <value>Repository that the app installation has access to</value>
        [DataMember(Name = "installation-repository", EmitDefaultValue = false)]
        public string InstallationRepository { get; set; }

        /// <summary>
        /// Set output format to JSON
        /// </summary>
        /// <value>Set output format to JSON</value>
        [DataMember(Name = "json", EmitDefaultValue = true)]
        public bool Json { get; set; }

        /// <summary>
        /// Producer name
        /// </summary>
        /// <value>Producer name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Target name
        /// </summary>
        /// <value>Target name</value>
        [DataMember(Name = "target-name", EmitDefaultValue = false)]
        public string TargetName { get; set; }

        /// <summary>
        /// Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)
        /// </summary>
        /// <value>Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)</value>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public string Token { get; set; }

        /// <summary>
        /// Optional - installation token&#39;s allowed permissions
        /// </summary>
        /// <value>Optional - installation token&#39;s allowed permissions</value>
        [DataMember(Name = "token-permissions", EmitDefaultValue = false)]
        public List<string> TokenPermissions { get; set; }

        /// <summary>
        /// Optional - installation token&#39;s allowed repositories
        /// </summary>
        /// <value>Optional - installation token&#39;s allowed repositories</value>
        [DataMember(Name = "token-repositories", EmitDefaultValue = false)]
        public List<string> TokenRepositories { get; set; }

        /// <summary>
        /// The universal identity token, Required only for universal_identity authentication
        /// </summary>
        /// <value>The universal identity token, Required only for universal_identity authentication</value>
        [DataMember(Name = "uid-token", EmitDefaultValue = false)]
        public string UidToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GatewayCreateProducerGithub {\n");
            sb.Append("  DeleteProtection: ").Append(DeleteProtection).Append("\n");
            sb.Append("  GithubAppId: ").Append(GithubAppId).Append("\n");
            sb.Append("  GithubAppPrivateKey: ").Append(GithubAppPrivateKey).Append("\n");
            sb.Append("  GithubBaseUrl: ").Append(GithubBaseUrl).Append("\n");
            sb.Append("  InstallationId: ").Append(InstallationId).Append("\n");
            sb.Append("  InstallationRepository: ").Append(InstallationRepository).Append("\n");
            sb.Append("  Json: ").Append(Json).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TargetName: ").Append(TargetName).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  TokenPermissions: ").Append(TokenPermissions).Append("\n");
            sb.Append("  TokenRepositories: ").Append(TokenRepositories).Append("\n");
            sb.Append("  UidToken: ").Append(UidToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GatewayCreateProducerGithub);
        }

        /// <summary>
        /// Returns true if GatewayCreateProducerGithub instances are equal
        /// </summary>
        /// <param name="input">Instance of GatewayCreateProducerGithub to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GatewayCreateProducerGithub input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DeleteProtection == input.DeleteProtection ||
                    (this.DeleteProtection != null &&
                    this.DeleteProtection.Equals(input.DeleteProtection))
                ) && 
                (
                    this.GithubAppId == input.GithubAppId ||
                    this.GithubAppId.Equals(input.GithubAppId)
                ) && 
                (
                    this.GithubAppPrivateKey == input.GithubAppPrivateKey ||
                    (this.GithubAppPrivateKey != null &&
                    this.GithubAppPrivateKey.Equals(input.GithubAppPrivateKey))
                ) && 
                (
                    this.GithubBaseUrl == input.GithubBaseUrl ||
                    (this.GithubBaseUrl != null &&
                    this.GithubBaseUrl.Equals(input.GithubBaseUrl))
                ) && 
                (
                    this.InstallationId == input.InstallationId ||
                    this.InstallationId.Equals(input.InstallationId)
                ) && 
                (
                    this.InstallationRepository == input.InstallationRepository ||
                    (this.InstallationRepository != null &&
                    this.InstallationRepository.Equals(input.InstallationRepository))
                ) && 
                (
                    this.Json == input.Json ||
                    this.Json.Equals(input.Json)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.TargetName == input.TargetName ||
                    (this.TargetName != null &&
                    this.TargetName.Equals(input.TargetName))
                ) && 
                (
                    this.Token == input.Token ||
                    (this.Token != null &&
                    this.Token.Equals(input.Token))
                ) && 
                (
                    this.TokenPermissions == input.TokenPermissions ||
                    this.TokenPermissions != null &&
                    input.TokenPermissions != null &&
                    this.TokenPermissions.SequenceEqual(input.TokenPermissions)
                ) && 
                (
                    this.TokenRepositories == input.TokenRepositories ||
                    this.TokenRepositories != null &&
                    input.TokenRepositories != null &&
                    this.TokenRepositories.SequenceEqual(input.TokenRepositories)
                ) && 
                (
                    this.UidToken == input.UidToken ||
                    (this.UidToken != null &&
                    this.UidToken.Equals(input.UidToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DeleteProtection != null)
                {
                    hashCode = (hashCode * 59) + this.DeleteProtection.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.GithubAppId.GetHashCode();
                if (this.GithubAppPrivateKey != null)
                {
                    hashCode = (hashCode * 59) + this.GithubAppPrivateKey.GetHashCode();
                }
                if (this.GithubBaseUrl != null)
                {
                    hashCode = (hashCode * 59) + this.GithubBaseUrl.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.InstallationId.GetHashCode();
                if (this.InstallationRepository != null)
                {
                    hashCode = (hashCode * 59) + this.InstallationRepository.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Json.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.TargetName != null)
                {
                    hashCode = (hashCode * 59) + this.TargetName.GetHashCode();
                }
                if (this.Token != null)
                {
                    hashCode = (hashCode * 59) + this.Token.GetHashCode();
                }
                if (this.TokenPermissions != null)
                {
                    hashCode = (hashCode * 59) + this.TokenPermissions.GetHashCode();
                }
                if (this.TokenRepositories != null)
                {
                    hashCode = (hashCode * 59) + this.TokenRepositories.GetHashCode();
                }
                if (this.UidToken != null)
                {
                    hashCode = (hashCode * 59) + this.UidToken.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
