/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// LeadershipConfigPart
    /// </summary>
    [DataContract(Name = "LeadershipConfigPart")]
    public partial class LeadershipConfigPart : IEquatable<LeadershipConfigPart>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeadershipConfigPart" /> class.
        /// </summary>
        /// <param name="openLeadership">openLeadership.</param>
        public LeadershipConfigPart(List<int> openLeadership = default(List<int>))
        {
            this.OpenLeadership = openLeadership;
        }

        /// <summary>
        /// Gets or Sets OpenLeadership
        /// </summary>
        [DataMember(Name = "open_leadership", EmitDefaultValue = false)]
        public List<int> OpenLeadership { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LeadershipConfigPart {\n");
            sb.Append("  OpenLeadership: ").Append(OpenLeadership).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LeadershipConfigPart);
        }

        /// <summary>
        /// Returns true if LeadershipConfigPart instances are equal
        /// </summary>
        /// <param name="input">Instance of LeadershipConfigPart to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LeadershipConfigPart input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OpenLeadership == input.OpenLeadership ||
                    this.OpenLeadership != null &&
                    input.OpenLeadership != null &&
                    this.OpenLeadership.SequenceEqual(input.OpenLeadership)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OpenLeadership != null)
                    hashCode = hashCode * 59 + this.OpenLeadership.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
