/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// OCIAccessRules contains access rules specific to Oracle cloud instance / user authentication
    /// </summary>
    [DataContract(Name = "OCIAccessRules")]
    public partial class OCIAccessRules : IEquatable<OCIAccessRules>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OCIAccessRules" /> class.
        /// </summary>
        /// <param name="groupOcids">groupOcids.</param>
        /// <param name="tenantOcid">tenantOcid.</param>
        public OCIAccessRules(List<string> groupOcids = default(List<string>), string tenantOcid = default(string))
        {
            this.GroupOcids = groupOcids;
            this.TenantOcid = tenantOcid;
        }

        /// <summary>
        /// Gets or Sets GroupOcids
        /// </summary>
        [DataMember(Name = "group_ocids", EmitDefaultValue = false)]
        public List<string> GroupOcids { get; set; }

        /// <summary>
        /// Gets or Sets TenantOcid
        /// </summary>
        [DataMember(Name = "tenant_ocid", EmitDefaultValue = false)]
        public string TenantOcid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OCIAccessRules {\n");
            sb.Append("  GroupOcids: ").Append(GroupOcids).Append("\n");
            sb.Append("  TenantOcid: ").Append(TenantOcid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OCIAccessRules);
        }

        /// <summary>
        /// Returns true if OCIAccessRules instances are equal
        /// </summary>
        /// <param name="input">Instance of OCIAccessRules to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OCIAccessRules input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.GroupOcids == input.GroupOcids ||
                    this.GroupOcids != null &&
                    input.GroupOcids != null &&
                    this.GroupOcids.SequenceEqual(input.GroupOcids)
                ) && 
                (
                    this.TenantOcid == input.TenantOcid ||
                    (this.TenantOcid != null &&
                    this.TenantOcid.Equals(input.TenantOcid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GroupOcids != null)
                {
                    hashCode = (hashCode * 59) + this.GroupOcids.GetHashCode();
                }
                if (this.TenantOcid != null)
                {
                    hashCode = (hashCode * 59) + this.TenantOcid.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
