/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// OCIAccessRules contains access rules specific to Oracle cloud instance / user authentication
    /// </summary>
    [DataContract(Name = "OCIAccessRules")]
    public partial class OCIAccessRules : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OCIAccessRules" /> class.
        /// </summary>
        /// <param name="groupOcids">groupOcids.</param>
        /// <param name="tenantOcid">tenantOcid.</param>
        public OCIAccessRules(List<string> groupOcids = default(List<string>), string tenantOcid = default(string))
        {
            this.GroupOcids = groupOcids;
            this.TenantOcid = tenantOcid;
        }

        /// <summary>
        /// Gets or Sets GroupOcids
        /// </summary>
        [DataMember(Name = "group_ocids", EmitDefaultValue = false)]
        public List<string> GroupOcids { get; set; }

        /// <summary>
        /// Gets or Sets TenantOcid
        /// </summary>
        [DataMember(Name = "tenant_ocid", EmitDefaultValue = false)]
        public string TenantOcid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OCIAccessRules {\n");
            sb.Append("  GroupOcids: ").Append(GroupOcids).Append("\n");
            sb.Append("  TenantOcid: ").Append(TenantOcid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
