/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// RoleAuthMethodAssociation includes details of an association between a role and an auth method.
    /// </summary>
    [DataContract(Name = "RoleAuthMethodAssociation")]
    public partial class RoleAuthMethodAssociation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RoleAuthMethodAssociation" /> class.
        /// </summary>
        /// <param name="assocId">assocId.</param>
        /// <param name="authMethodAccessId">authMethodAccessId.</param>
        /// <param name="authMethodName">authMethodName.</param>
        /// <param name="authMethodSubClaims">authMethodSubClaims.</param>
        /// <param name="isSubclaimsWithOperator">isSubclaimsWithOperator.</param>
        /// <param name="subClaimsCaseSensitive">subClaimsCaseSensitive.</param>
        public RoleAuthMethodAssociation(string assocId = default(string), string authMethodAccessId = default(string), string authMethodName = default(string), Dictionary<string, List<string>> authMethodSubClaims = default(Dictionary<string, List<string>>), bool isSubclaimsWithOperator = default(bool), bool subClaimsCaseSensitive = default(bool))
        {
            this.AssocId = assocId;
            this.AuthMethodAccessId = authMethodAccessId;
            this.AuthMethodName = authMethodName;
            this.AuthMethodSubClaims = authMethodSubClaims;
            this.IsSubclaimsWithOperator = isSubclaimsWithOperator;
            this.SubClaimsCaseSensitive = subClaimsCaseSensitive;
        }

        /// <summary>
        /// Gets or Sets AssocId
        /// </summary>
        [DataMember(Name = "assoc_id", EmitDefaultValue = false)]
        public string AssocId { get; set; }

        /// <summary>
        /// Gets or Sets AuthMethodAccessId
        /// </summary>
        [DataMember(Name = "auth_method_access_id", EmitDefaultValue = false)]
        public string AuthMethodAccessId { get; set; }

        /// <summary>
        /// Gets or Sets AuthMethodName
        /// </summary>
        [DataMember(Name = "auth_method_name", EmitDefaultValue = false)]
        public string AuthMethodName { get; set; }

        /// <summary>
        /// Gets or Sets AuthMethodSubClaims
        /// </summary>
        [DataMember(Name = "auth_method_sub_claims", EmitDefaultValue = false)]
        public Dictionary<string, List<string>> AuthMethodSubClaims { get; set; }

        /// <summary>
        /// Gets or Sets IsSubclaimsWithOperator
        /// </summary>
        [DataMember(Name = "is_subclaims_with_operator", EmitDefaultValue = true)]
        public bool IsSubclaimsWithOperator { get; set; }

        /// <summary>
        /// Gets or Sets SubClaimsCaseSensitive
        /// </summary>
        [DataMember(Name = "sub_claims_case_sensitive", EmitDefaultValue = true)]
        public bool SubClaimsCaseSensitive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RoleAuthMethodAssociation {\n");
            sb.Append("  AssocId: ").Append(AssocId).Append("\n");
            sb.Append("  AuthMethodAccessId: ").Append(AuthMethodAccessId).Append("\n");
            sb.Append("  AuthMethodName: ").Append(AuthMethodName).Append("\n");
            sb.Append("  AuthMethodSubClaims: ").Append(AuthMethodSubClaims).Append("\n");
            sb.Append("  IsSubclaimsWithOperator: ").Append(IsSubclaimsWithOperator).Append("\n");
            sb.Append("  SubClaimsCaseSensitive: ").Append(SubClaimsCaseSensitive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
