/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// TargetCreateAerospike
    /// </summary>
    [DataContract(Name = "targetCreateAerospike")]
    public partial class TargetCreateAerospike : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TargetCreateAerospike" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TargetCreateAerospike() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TargetCreateAerospike" /> class.
        /// </summary>
        /// <param name="adminUsername">Username of an account with the user-admin role.</param>
        /// <param name="aerospikeClientId">Client ID for Aerospike Cloud authentication (relevant only for Aerospike Cloud).</param>
        /// <param name="aerospikeClientSecret">Client secret for Aerospike Cloud authentication (relevant only for Aerospike Cloud).</param>
        /// <param name="aerospikeCloud">Set to &#39;true&#39; for Aerospike Cloud deployments.</param>
        /// <param name="aerospikeClusterId">Cloud cluster ID (relevant only for Aerospike Cloud).</param>
        /// <param name="clientCertificate">Client certificate for mTLS (mTLS only).</param>
        /// <param name="clientPrivateKey">Client private key for mTLS (mTLS only).</param>
        /// <param name="dbServerName">TLS server name used to verify the certificate hostname. If empty, the Aerospike hostname is used..</param>
        /// <param name="deleteProtection">Protection from accidental deletion of this object [true/false].</param>
        /// <param name="description">Description of the object.</param>
        /// <param name="enableMtls">Enable mutual TLS authentication - requires - -ssl&#x3D;true (true/false).</param>
        /// <param name="hostname">Aerospike host address and port (e.g. url.to.aerospike.db).</param>
        /// <param name="json">Set output format to JSON (default to false).</param>
        /// <param name="key">The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used).</param>
        /// <param name="maxVersions">Set the maximum number of versions, limited by the account settings defaults..</param>
        /// <param name="name">Target name (required).</param>
        /// <param name="varNamespace">Namespace name (relevant only for Aerospike db).</param>
        /// <param name="password">Password for the admin user.</param>
        /// <param name="port">Database connection port.</param>
        /// <param name="skipServerNameValidation">Skip server name verification while still validating the certificate chain (true/false). Empty means do not skip..</param>
        /// <param name="ssl">Enable SSL encryption (true/false).</param>
        /// <param name="sslCertificate">Base64-encoded SSL CA certificate from a trusted Certificate Authority (CA).</param>
        /// <param name="token">Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;).</param>
        /// <param name="uidToken">The universal identity token, Required only for universal_identity authentication.</param>
        public TargetCreateAerospike(string adminUsername = default(string), string aerospikeClientId = default(string), string aerospikeClientSecret = default(string), bool aerospikeCloud = default(bool), string aerospikeClusterId = default(string), string clientCertificate = default(string), string clientPrivateKey = default(string), string dbServerName = default(string), string deleteProtection = default(string), string description = default(string), bool enableMtls = default(bool), string hostname = default(string), bool json = false, string key = default(string), string maxVersions = default(string), string name = default(string), string varNamespace = default(string), string password = default(string), string port = default(string), string skipServerNameValidation = default(string), bool ssl = default(bool), string sslCertificate = default(string), string token = default(string), string uidToken = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for TargetCreateAerospike and cannot be null");
            }
            this.Name = name;
            this.AdminUsername = adminUsername;
            this.AerospikeClientId = aerospikeClientId;
            this.AerospikeClientSecret = aerospikeClientSecret;
            this.AerospikeCloud = aerospikeCloud;
            this.AerospikeClusterId = aerospikeClusterId;
            this.ClientCertificate = clientCertificate;
            this.ClientPrivateKey = clientPrivateKey;
            this.DbServerName = dbServerName;
            this.DeleteProtection = deleteProtection;
            this.Description = description;
            this.EnableMtls = enableMtls;
            this.Hostname = hostname;
            this.Json = json;
            this.Key = key;
            this.MaxVersions = maxVersions;
            this.Namespace = varNamespace;
            this.Password = password;
            this.Port = port;
            this.SkipServerNameValidation = skipServerNameValidation;
            this.Ssl = ssl;
            this.SslCertificate = sslCertificate;
            this.Token = token;
            this.UidToken = uidToken;
        }

        /// <summary>
        /// Username of an account with the user-admin role
        /// </summary>
        /// <value>Username of an account with the user-admin role</value>
        [DataMember(Name = "admin-username", EmitDefaultValue = false)]
        public string AdminUsername { get; set; }

        /// <summary>
        /// Client ID for Aerospike Cloud authentication (relevant only for Aerospike Cloud)
        /// </summary>
        /// <value>Client ID for Aerospike Cloud authentication (relevant only for Aerospike Cloud)</value>
        [DataMember(Name = "aerospike-client-id", EmitDefaultValue = false)]
        public string AerospikeClientId { get; set; }

        /// <summary>
        /// Client secret for Aerospike Cloud authentication (relevant only for Aerospike Cloud)
        /// </summary>
        /// <value>Client secret for Aerospike Cloud authentication (relevant only for Aerospike Cloud)</value>
        [DataMember(Name = "aerospike-client-secret", EmitDefaultValue = false)]
        public string AerospikeClientSecret { get; set; }

        /// <summary>
        /// Set to &#39;true&#39; for Aerospike Cloud deployments
        /// </summary>
        /// <value>Set to &#39;true&#39; for Aerospike Cloud deployments</value>
        [DataMember(Name = "aerospike-cloud", EmitDefaultValue = true)]
        public bool AerospikeCloud { get; set; }

        /// <summary>
        /// Cloud cluster ID (relevant only for Aerospike Cloud)
        /// </summary>
        /// <value>Cloud cluster ID (relevant only for Aerospike Cloud)</value>
        [DataMember(Name = "aerospike-cluster-id", EmitDefaultValue = false)]
        public string AerospikeClusterId { get; set; }

        /// <summary>
        /// Client certificate for mTLS (mTLS only)
        /// </summary>
        /// <value>Client certificate for mTLS (mTLS only)</value>
        [DataMember(Name = "client-certificate", EmitDefaultValue = false)]
        public string ClientCertificate { get; set; }

        /// <summary>
        /// Client private key for mTLS (mTLS only)
        /// </summary>
        /// <value>Client private key for mTLS (mTLS only)</value>
        [DataMember(Name = "client-private-key", EmitDefaultValue = false)]
        public string ClientPrivateKey { get; set; }

        /// <summary>
        /// TLS server name used to verify the certificate hostname. If empty, the Aerospike hostname is used.
        /// </summary>
        /// <value>TLS server name used to verify the certificate hostname. If empty, the Aerospike hostname is used.</value>
        [DataMember(Name = "db-server-name", EmitDefaultValue = false)]
        public string DbServerName { get; set; }

        /// <summary>
        /// Protection from accidental deletion of this object [true/false]
        /// </summary>
        /// <value>Protection from accidental deletion of this object [true/false]</value>
        [DataMember(Name = "delete_protection", EmitDefaultValue = false)]
        public string DeleteProtection { get; set; }

        /// <summary>
        /// Description of the object
        /// </summary>
        /// <value>Description of the object</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Enable mutual TLS authentication - requires - -ssl&#x3D;true (true/false)
        /// </summary>
        /// <value>Enable mutual TLS authentication - requires - -ssl&#x3D;true (true/false)</value>
        [DataMember(Name = "enable-mtls", EmitDefaultValue = true)]
        public bool EnableMtls { get; set; }

        /// <summary>
        /// Aerospike host address and port (e.g. url.to.aerospike.db)
        /// </summary>
        /// <value>Aerospike host address and port (e.g. url.to.aerospike.db)</value>
        [DataMember(Name = "hostname", EmitDefaultValue = false)]
        public string Hostname { get; set; }

        /// <summary>
        /// Set output format to JSON
        /// </summary>
        /// <value>Set output format to JSON</value>
        [DataMember(Name = "json", EmitDefaultValue = true)]
        public bool Json { get; set; }

        /// <summary>
        /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
        /// </summary>
        /// <value>The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)</value>
        [DataMember(Name = "key", EmitDefaultValue = false)]
        public string Key { get; set; }

        /// <summary>
        /// Set the maximum number of versions, limited by the account settings defaults.
        /// </summary>
        /// <value>Set the maximum number of versions, limited by the account settings defaults.</value>
        [DataMember(Name = "max-versions", EmitDefaultValue = false)]
        public string MaxVersions { get; set; }

        /// <summary>
        /// Target name
        /// </summary>
        /// <value>Target name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Namespace name (relevant only for Aerospike db)
        /// </summary>
        /// <value>Namespace name (relevant only for Aerospike db)</value>
        [DataMember(Name = "namespace", EmitDefaultValue = false)]
        public string Namespace { get; set; }

        /// <summary>
        /// Password for the admin user
        /// </summary>
        /// <value>Password for the admin user</value>
        [DataMember(Name = "password", EmitDefaultValue = false)]
        public string Password { get; set; }

        /// <summary>
        /// Database connection port
        /// </summary>
        /// <value>Database connection port</value>
        [DataMember(Name = "port", EmitDefaultValue = false)]
        public string Port { get; set; }

        /// <summary>
        /// Skip server name verification while still validating the certificate chain (true/false). Empty means do not skip.
        /// </summary>
        /// <value>Skip server name verification while still validating the certificate chain (true/false). Empty means do not skip.</value>
        [DataMember(Name = "skip-server-name-validation", EmitDefaultValue = false)]
        public string SkipServerNameValidation { get; set; }

        /// <summary>
        /// Enable SSL encryption (true/false)
        /// </summary>
        /// <value>Enable SSL encryption (true/false)</value>
        [DataMember(Name = "ssl", EmitDefaultValue = true)]
        public bool Ssl { get; set; }

        /// <summary>
        /// Base64-encoded SSL CA certificate from a trusted Certificate Authority (CA)
        /// </summary>
        /// <value>Base64-encoded SSL CA certificate from a trusted Certificate Authority (CA)</value>
        [DataMember(Name = "ssl-certificate", EmitDefaultValue = false)]
        public string SslCertificate { get; set; }

        /// <summary>
        /// Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)
        /// </summary>
        /// <value>Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)</value>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public string Token { get; set; }

        /// <summary>
        /// The universal identity token, Required only for universal_identity authentication
        /// </summary>
        /// <value>The universal identity token, Required only for universal_identity authentication</value>
        [DataMember(Name = "uid-token", EmitDefaultValue = false)]
        public string UidToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TargetCreateAerospike {\n");
            sb.Append("  AdminUsername: ").Append(AdminUsername).Append("\n");
            sb.Append("  AerospikeClientId: ").Append(AerospikeClientId).Append("\n");
            sb.Append("  AerospikeClientSecret: ").Append(AerospikeClientSecret).Append("\n");
            sb.Append("  AerospikeCloud: ").Append(AerospikeCloud).Append("\n");
            sb.Append("  AerospikeClusterId: ").Append(AerospikeClusterId).Append("\n");
            sb.Append("  ClientCertificate: ").Append(ClientCertificate).Append("\n");
            sb.Append("  ClientPrivateKey: ").Append(ClientPrivateKey).Append("\n");
            sb.Append("  DbServerName: ").Append(DbServerName).Append("\n");
            sb.Append("  DeleteProtection: ").Append(DeleteProtection).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  EnableMtls: ").Append(EnableMtls).Append("\n");
            sb.Append("  Hostname: ").Append(Hostname).Append("\n");
            sb.Append("  Json: ").Append(Json).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  MaxVersions: ").Append(MaxVersions).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Namespace: ").Append(Namespace).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  SkipServerNameValidation: ").Append(SkipServerNameValidation).Append("\n");
            sb.Append("  Ssl: ").Append(Ssl).Append("\n");
            sb.Append("  SslCertificate: ").Append(SslCertificate).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  UidToken: ").Append(UidToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
