/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = akeyless.Client.OpenAPIDateConverter;

namespace akeyless.Model
{
    /// <summary>
    /// UscListSecretsOutput
    /// </summary>
    [DataContract(Name = "UscListSecretsOutput")]
    public partial class UscListSecretsOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UscListSecretsOutput" /> class.
        /// </summary>
        /// <param name="nextToken">nextToken.</param>
        /// <param name="secretsList">secretsList.</param>
        /// <param name="warnings">warnings.</param>
        public UscListSecretsOutput(string nextToken = default(string), List<SecretInfo> secretsList = default(List<SecretInfo>), List<string> warnings = default(List<string>))
        {
            this.NextToken = nextToken;
            this.SecretsList = secretsList;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Gets or Sets NextToken
        /// </summary>
        [DataMember(Name = "next_token", EmitDefaultValue = false)]
        public string NextToken { get; set; }

        /// <summary>
        /// Gets or Sets SecretsList
        /// </summary>
        [DataMember(Name = "secrets_list", EmitDefaultValue = false)]
        public List<SecretInfo> SecretsList { get; set; }

        /// <summary>
        /// Gets or Sets Warnings
        /// </summary>
        [DataMember(Name = "warnings", EmitDefaultValue = false)]
        public List<string> Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UscListSecretsOutput {\n");
            sb.Append("  NextToken: ").Append(NextToken).Append("\n");
            sb.Append("  SecretsList: ").Append(SecretsList).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
